services:
  - type: web
    name: jain-rag-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn chatbot:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USERNAME
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: GROQ_API_KEY
        sync: false
